---
title: "Smoothing spline"
author: "KJG"
date: \today
output:
  pdf_document:
    includes:
      in_header: Markdown.tex
    number_sections: yes
  html_document:
    df_print: paged
fontsize: 11pt
editor_options:
  chunk_output_type: console
---

```{r}
g = function(x, vecg)
{
	gamma = solve(R) %*% t(Q) %*% vecg
	gamma = c(0,gamma,0)

	gprime1 = (vecg[2] - vecg[1])/h[1] - (1/6) * h[1] * gamma[2]
	gprimen = (vecg[n] - vecg[n-1])/h[n-1] + (1/6) * h[n-1] * gamma[n-1]
	Sum = 0

	for(i in 1 : (n-1))
	{
		Summand = (((x - X[i]) * vecg[i + 1] + (X[i + 1] - x) * vecg[i])/h[i] - (1/6) * (x - X[i]) * (X[i + 1]-x) * ((1 + (x - X[i])/h[i]) * gamma[i + 1] + (1 + (X[i + 1] - x)/h[i]) * gamma[i])) * (x >= X[i]) * (x < X[i + 1])

		Sum = Sum + Summand
	}

	Sum = Sum + (vecg[1] - (X[1] - x) * gprime1) * (x >=0) * (x < X[1]) + (vecg[n] + (x - X[n]) * gprimen) * (x >= X[n]) * (x <= 1)

	return(Sum)
}

lambdas_all = function(number_lambdas, lambda_max, epsilon_lambda)
{
   if(number_lambdas == 1)
   {
      h = lambda_max
   }
   else
   {
      h = rep(0, number_lambdas)
      lambda_min = (epsilon_lambda * lambda_max)
      ratio_max_min = (1 / epsilon_lambda)
      div = (number_lambdas - 1)
      for( lambda_index in 1:number_lambdas )
      {
         exponent = (lambda_index - 1) / div
         h[lambda_index] = lambda_min * ratio_max_min^exponent
      }
      h[1] = 0
   }
   return(h)
}
```

# To illustrate natural cubic spline interpolant and regression estimator
```{r}
set.seed(101)

n = 500
X = seq(0, 30, length.out = n)
h = diff(X)
# f = sin(2 * pi * X)
f = 2 * exp(-((X-8)^2/0.01))
# 30 * exp(-((X-2)^2/0.01)) + 
Y = f + rnorm(n, sd = 0.1)
plot(X, Y, pch = 20,
     xlab = "x", ylab = "y", main = "Cubic Spline",
     cex = 1, lwd = 2)
```


```{r}
set.seed(101)

n = 40
X = seq(0, 1, length.out = n)
h = diff(X)
f = sin(2 * pi * X)
Y = f + rnorm(n, sd = 0.3)
plot(X, Y, pch = 20,
     xlab = "x", ylab = "y", main = "Cubic Spline",
     cex = 1, lwd = 2, col = "grey40")
```

```{r}
n = length(X)
R = matrix(0,n-2,n-2)

for(i in 1:(n-2)) R[i,i] <- (h[i]+h[i+1])/3
for(i in 1:(n-3))
	{
	R[i,i+1] <- h[i+1]/6
	R[i+1,i] <- h[i+1]/6
	}

Q <- matrix(0,n,n-2)

for(i in 1:(n-2))
	{
	Q[i,i] <- 1/h[i]
	Q[i+1,i] <- -1/h[i] - 1/h[i+1]
	Q[i+2,i] <- 1/h[i+1]
	}
```

# lambda grid generation
```{r}
number_lambdas = 100
lambda_max = 10
epsilon_lambda = 10e-10

lambda = lambdas_all(number_lambdas, lambda_max, epsilon_lambda)
```

```{r}
cv_score = rep(NA, number_lambdas)
vecg = matrix(NA, nrow = number_lambdas, ncol = length(X))

for(i in 1 : number_lambdas)
{
   K = Q %*% solve(R) %*% t(Q)
   vecg[i, ] = solve(diag(rep(1, n)) + lambda[i] * K) %*% Y
   A = solve(diag(rep(1, n)) + lambda[i] * K)
   diag_A = diag(A)
   cv_score[i] = mean( ((Y - vecg[i, ])/(1 - diag_A))^2 )
}
```

```{r}
# pdf("spline.pdf", width = 7, height = 7, onefile = TRUE)
par(mfrow = c(1, 1))
plot(X, Y, pch = 20,
     xlab = "x", ylab = "y", main = "Smoothing spline illustration",
     cex = 1, lwd = 1.5, col = "grey40")

col = topo.colors(number_lambdas)

lm = lm(Y ~ X)
abline(a = lm$coefficients[1], b = lm$coefficients[2], lty = 2)

for (i in 1 : number_lambdas)
{
   points(X, vecg[i,], pch = 20, lty = 3, col = col[i], cex = 0.6)
}

lambda_opt = lambda[which.min(cv_score)]
K = Q %*% solve(R) %*% t(Q)
vecg2 = solve(diag(rep(1, n)) + lambda_opt * K) %*% Y

x_grid = seq(0, 30, length.out = 1000)
# f_grid = sin(2 * pi * x_grid)
# f_grid = 30 * exp(-((x_grid-2)^2/0.05))
lines(x = x_grid, y = g(x_grid, vecg2), col = "forestgreen", lwd = 1.5)
# lines(x = x_grid, y = f_grid, col = "blue", lty = 5, lwd = 1.5)

points(X, vecg[which.min(cv_score), ], pch = 20, lty = 3, col = "forestgreen", cex = 1)



legend("topright",
       legend = c("natural cubic spline (GCV)",
                  "true function",
                  "least squares"),
       lty = c(1, 5, 2),
       col = c("forestgreen",
               "blue",
               "black"),
       # box.col = "white",
       bg = "white",
       title = "lines")
# dev.off()
```